import { Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'next title',
    template: '%s | title'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'lightblue' }}>Header</header>
        {children}
        <footer style={{background: 'lightblue'}}>Footer</footer>
      </body>
    </html>
  )
}
